=== JiangbinZhang/glotaran-1.5/JAXBWizzardOutput/src/main/resources/xml-resources/jaxb/SpectralModelSpecification/SpectralModelSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://glotaran.org/schema/SpectralModelSchema"
            xmlns:tns="http://glotaran.org/schema/SpectralModelSchema"
            elementFormDefault="qualified">
    <xsd:element name="SpectralModelSpecification">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="lambdaMin" type="xsd:double"/>
                <xsd:element name="lambdaMax" type="xsd:double"/>
                <xsd:element name="lamdaStep" type="xsd:double"/>
                <xsd:element name="timeMin" type="xsd:double"/>
                <xsd:element name="timeMax" type="xsd:double"/>
                <xsd:element name="timeStep" type="xsd:double"/>
                <xsd:element name="lowerLinearTimeBound" type="xsd:double" nillable="true" minOccurs="1"/>
                <xsd:element name="upperLinearTimeBound" type="xsd:double" nillable="true" minOccurs="1"/>
                <xsd:element name="spectras" type="tns:Spectra" minOccurs="0" maxOccurs="unbounded" nillable="true"/>
                <xsd:element name="noiseType" type="xsd:string" nillable="true" minOccurs="1"/>
                <xsd:element name="noiseAmplitude" type="xsd:double" nillable="true" minOccurs="1"/>
                <xsd:element name="noiseSeed" type="xsd:int" minOccurs="1" nillable="true"/>
                <xsd:element name="numberOfLogPoints" type="xsd:int" nillable="true"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="Spectra">
        <xsd:sequence>
            <xsd:element name="amplitude" type="xsd:double"/>
            <xsd:element name="mean" type="xsd:double"/>
            <xsd:element name="width" type="xsd:double"/>
            <xsd:element name="skewness" type="xsd:double"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== JiangbinZhang/glotaran-1.5/SimSupport/src/main/resources/org/glotaran/simfilesupport/SpectralModelTemplate.xml
<?xml version="1.0" encoding="UTF-8"?>

<ns0:SpectralModelSpecification  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://glotaran.org/schema/SpectralModelSchema'
   xsi:schemaLocation='http://glotaran.org/schema/SpectralModelSchema SpectralModelSchema.xsd'>
    <ns0:lambdaMin></ns0:lambdaMin>
    <ns0:lambdaMax></ns0:lambdaMax>
    <ns0:lamdaStep></ns0:lamdaStep>
    <ns0:timeMin></ns0:timeMin>
    <ns0:timeMax></ns0:timeMax>
    <ns0:timeStep></ns0:timeStep>
    <ns0:lowerLinearTimeBound></ns0:lowerLinearTimeBound>
    <ns0:upperLinearTimeBound></ns0:upperLinearTimeBound>
    <ns0:noiseType></ns0:noiseType>
    <ns0:noiseAmplitude></ns0:noiseAmplitude>
    <ns0:noiseSeed></ns0:noiseSeed>
    <ns0:numberOfLogPoints></ns0:numberOfLogPoints>

</ns0:SpectralModelSpecification>
